In [6]:
from Landscapes import *
import numpy as np

In [2]:
def make_Dirichland(N,K, concentration_params):

    our_dirichlet = stats.dirichlet(concentration_params) #the distribution we use

    NK_land = np.zeros((N,2**(K+1)))
    
    fitnesses = []
    permutations = []
    
    all_permutations = list(itertools.product([0,1],repeat=N))

    for permutation in all_permutations:

        genome_fitness = 0
        for currentCharacteristic in np.arange(N):
            #get the fitness indices from each k based upon local gene values
            
            localgenes = permutation[currentCharacteristic:currentCharacteristic+K+1]
            
            #loop through to next if were are near the nth index
            if currentCharacteristic+K+1 > N:
                localgenes = np.append(localgenes,permutation[0:currentCharacteristic-(N-K)+1])
                indices = list(range(currentCharacteristic,N)) + list(range(currentCharacteristic-(N-K)+1))
            else:
                indices = list(range(currentCharacteristic,currentCharacteristic+K+1))
            
            #get index fitness  is stored at
            interactIndex = ((2**(np.arange(K+1)*(localgenes)))*localgenes).sum()
            
            currentVal = NK_land[currentCharacteristic,interactIndex]
            #print(currentCharacteristic, interactIndex, currentVal)
            if currentVal == 0:
                dir_draw = our_dirichlet.rvs()[0]
                
                currentValues= dir_draw[indices]
                print(indices,currentValues)
                NK_land[currentCharacteristic,interactIndex] = sum(currentValues)
            
            #add current value to the running fitness total

            genome_fitness += sum(currentValues)
        
        fitnesses.append(genome_fitness)
        permutations.append("".join([str(i) for i in permutation]))
    print(NK_land)

    df = pd.DataFrame(fitnesses,index=permutations,columns=["Fitness"])
    df.loc[:,'Location'] = all_permutations

    return df

In [3]:
N=10
K=8
concentration_params =  [10,10,10,10,200,200,10,10,10,10]
scalar = 1

assert len(concentration_params) == N, "Concentrations params wrong for given N"

In [43]:
concentration_params =  [10,10,10,10,20,20,10,10,10,10]
our_dirichlet = stats.dirichlet(concentration_params)


In [44]:
draws = our_dirichlet.rvs(1000)

In [45]:
np.mean(draws,axis=0)

array([0.0845924 , 0.08236798, 0.0836052 , 0.08419014, 0.16685006,
       0.16627901, 0.08493181, 0.0832057 , 0.08100562, 0.08297207])

In [46]:
np.std(draws, axis=0)

array([0.02595364, 0.02456713, 0.02500155, 0.02471222, 0.03288824,
       0.03240466, 0.02458692, 0.02526501, 0.02449214, 0.02498179])

In [38]:
np.mean(draws_two,axis=0)

array([0.02109758, 0.02165642, 0.02140048, 0.02148325, 0.41935942,
       0.41144778, 0.02104631, 0.01968209, 0.02159682, 0.02122985])

In [39]:
np.std(draws_two,axis=0)

array([0.00633901, 0.00718397, 0.00622577, 0.00671212, 0.02355341,
       0.02067061, 0.00685173, 0.0072983 , 0.00546801, 0.0066173 ])